version: "3.9"

services:
  rss-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsradar-rss-worker
    env_file:
      .env
    environment:
      PYTHONUNBUFFERED: "1"
    command: ["python", "/app/scripts/rss_worker/main.py"]
    depends_on:
      mongo-handler:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "/app/scripts/rss_worker/test.py"]
      interval: 10s
      retries: 1
      start_period: 2s
    networks:
      - newsradar_net