# Nombre variables de entorno

VARENV_USUARIO_MONGODB_ROOT = "MONGO_INITDB_ROOT_USERNAME"
VARENV_CONTRASEÑA_MONGODB_ROOT = "MONGO_INITDB_ROOT_PASSWORD"
VARENV_PUERTO_LOCAL_MONGODB = "MONGO_LOCAL_PORT"

__all__ = [
    "VARENV_USUARIO_MONGODB_ROOT",
    "VARENV_CONTRASEÑA_MONGODB_ROOT",
    "VARENV_PUERTO_LOCAL_MONGODB"
]