# Nombre variables de entorno

VARENV_MONGO_USUARIO_ROOT = "MONGO_INITDB_ROOT_USERNAME"
VARENV_MONGO_CONTRASEÑA_ROOT = "MONGO_INITDB_ROOT_PASSWORD"
VARENV_INITDB_DATABASE = "MONGO_INITDB_DATABASE"
VARENV_MONGO_HOST = "MONGO_HOST"
VARENV_USUARIO_MONGODB_APP = "MONGO_APP_USER"
VARENV_CONTRASEÑA_MONGODB_APP = "MONGO_APP_PASSWORD"
VARENV_PUERTO_MONGODB = "MONGO_PORT"
VARENV_APP_DB_NAME = "MONGO_APP_DB"

__all__ = [
    "VARENV_MONGO_USUARIO_ROOT",
    "VARENV_MONGO_CONTRASEÑA_ROOT",
    "VARENV_INITDB_DATABASE",
    "VARENV_MONGO_HOST",
    "VARENV_USUARIO_MONGODB_APP",
    "VARENV_CONTRASEÑA_MONGODB_APP",
    "VARENV_PUERTO_MONGODB",
    "VARENV_APP_DB_NAME",
]
