# Nombre variables de entorno

VARENV_USUARIO_MONGODB_ROOT = "MONGO_ROOT_USERNAME"
VARENV_CONTRASEÑA_MONGODB_ROOT = "MONGO_ROOT_PASSWORD"
VARENV_PUERTO_LOCAL_MONGODB = "MONGO_EXPOSE_PORT"
VARENV_APP_DB = "MONGO_APP_DB"

__all__ = [
    "VARENV_USUARIO_MONGODB_ROOT",
    "VARENV_CONTRASEÑA_MONGODB_ROOT",
    "VARENV_PUERTO_LOCAL_MONGODB",
    "VARENV_APP_DB"
]