# Nombre variables de entorno

# Root
VARENV_MONGO_USUARIO_ROOT = "MONGO_ROOT_USERNAME"
VARENV_MONGO_CONTRASEÑA_ROOT = "MONGO_ROOT_PASSWORD"
VARENV_INITDB_DATABASE = "MONGO_INITDB_DATABASE"
VARENV_MONGO_HOST = "MONGO_HOST"

# User
VARENV_USUARIO_MONGODB_APP = "MONGO_APP_USER"
VARENV_CONTRASEÑA_MONGODB_APP = "MONGO_APP_PASSWORD"
VARENV_PUERTO_LOCAL_MONGODB = "MONGO_EXPOSE_PORT"
VARENV_APP_DB = "MONGO_APP_DB"

__all__ = [
    # Root
    "VARENV_MONGO_USUARIO_ROOT",
    "VARENV_MONGO_CONTRASEÑA_ROOT",
    "VARENV_INITDB_DATABASE",
    "VARENV_MONGO_HOST",
    
    # User
    "VARENV_USUARIO_MONGODB_APP",
    "VARENV_CONTRASEÑA_MONGODB_APP",
    "VARENV_PUERTO_LOCAL_MONGODB",
    "VARENV_APP_DB"
]