name: NewsRadar Sprint 1 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verificar ausencia de .env real
        run: |
          if [ -f .env ]; then echo "Error: .env detectado en el repo"; exit 1; fi

      # Usamos las contraseñas del .env.example para que todo sea coherente
      - name: Crear .env temporal
        run: |
          cp .env.example .env

      - name: Build y Up de Docker
        run: docker compose up -d --build

      - name: Esperar a que los servicios estén listos
        run: sleep 60

      - name: Check Health Endpoints
        run: |
          docker ps
          curl -f http://localhost:8000/health || exit 1

      - name: Ejecutar Tests Unitarios e Integración (Pytest)
        run: |
          docker exec \
            -e MONGODB_URI="mongodb://newsradar_root:change_me_root_pwd@newsradar-mongodb:27017/admin?authSource=admin" \
            -e SMTP_PASSWORD="mwliwwhxoioebhte" \
            newsradar-backend pytest -s test/test_sprint1.py
